workflows:
  build-and-distribute-android-app:
    name: Build and Distribute Android App
    max_build_duration: 60
    environment:
      flutter: 2.2.3
      node: 14
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Install Firebase CLI
        script: |
          curl -sL https://firebase.tools | bash
      - name: Firebase login
        script: |
          firebase login:ci --no-localhost
      - name: Distribute APK to Firebase App Distribution
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --release-notes "Release notes here" \
          --groups "test-group" # Replace with your Firebase App Distribution group name
