workflows:
  default-workflow:
    name: Default Workflow
    environment:
     vars:
        NODE_VERSION: "16" # Set Node.js version
      flutter: "2.2.3"
      node: "14"
    scripts:
     - name: Clear npm cache
       script: npm cache clean --force
     - name: Install dependencies
       script: npm install --verbose
     - name: Build the project
       script: npm run build
    artifacts:
      files:
        - build/
    publishing:
      email:
         recipients:
           - kengyap@upm.edu.my # Add teacher's email for testing